"""
Seed corpus — what the validator already knows the answer to.

Loaded from `seed_corpus.json` (versioned in repo, regenerated by
`scripts/refresh_seed.py` against the live network). Keeping it in JSON
rather than baked into code means non-developers can audit it.

Shape:
    {
      "version": 1,
      "generated_at": "2026-05-18T...",
      "trusted_nodes": ["https://node.gitlawb.com"],
      "cids": ["bafy...", ...],          // CIDv1 git objects
      "repos": [{"owner":"...", "repo":"..."}],
      "gossip_repos": [{"owner":"...", "repo":"...", "ref":"refs/heads/main"}]
    }
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import List

_CORPUS_PATH = os.environ.get(
    "GITLAWBNET_SEED_CORPUS",
    os.path.join(os.path.dirname(__file__), "..", "..", "seed_corpus.json"),
)


@dataclass
class Repo:
    owner: str
    repo: str


@dataclass
class GossipRepo:
    owner: str
    repo: str
    ref: str


@dataclass
class SeedCorpus:
    trusted_nodes: List[str]
    cids: List[str]
    repos: List[Repo]
    gossip_repos: List[GossipRepo]


def load() -> SeedCorpus:
    """Load the corpus from disk. Returns an empty corpus if the file is
    missing — challenges that depend on it will be skipped, not crash."""
    path = os.path.abspath(_CORPUS_PATH)
    if not os.path.exists(path):
        return SeedCorpus(
            trusted_nodes=["https://node.gitlawb.com"],
            cids=[],
            repos=[],
            gossip_repos=[],
        )
    with open(path) as f:
        data = json.load(f)
    return SeedCorpus(
        trusted_nodes=list(data.get("trusted_nodes", ["https://node.gitlawb.com"])),
        cids=list(data.get("cids", [])),
        repos=[Repo(**r) for r in data.get("repos", [])],
        gossip_repos=[GossipRepo(**r) for r in data.get("gossip_repos", [])],
    )
